### ISSUE TITLE
Tests fail on install via Panda

### ISSUE THREAD

**Issue by qlx4r** [bbkr/jsonrpc#15]
perl6 version:
> This is perl6 version 2015.07.1-868-g5cc2563 built on MoarVM version 2015.08-15-g4b427ed

I was trying to install `JSON::RPC` via panda and the tests failed on me. Here is the output:

    qlx4r@qp11 ~$ panda install JSON::RPC
    ==> Fetching JSON::RPC
    ==> Building JSON::RPC
    ==> Testing JSON::RPC

    # Failed test 'rpc call Batch (all notifications)'
    # at t/client.t line 190
    # Died

    # Failed test 'rpc call Batch (all notifications) validate'
    # at t/client.t line 195
    # Actual type: Any

    # Failed test 'not ordered Batch'
    # at t/client.t line 237
    # Died

    # Failed test 'not ordered Batch validate'
    # at t/client.t line 242
    # expected: 'pong'
    #      got: '7'

    # Failed test 'not ordered Batch validate'
    # at t/client.t line 243
    # expected: 'ping'
    #      got: '19'

    # Failed test 'duplicated id in Batch'
    # at t/client.t line 257
    # Died

    # Failed test 'duplicated id in Batch validate'
    # at t/client.t line 262
    # expected: 'pong'
    #      got: '7'

    # Failed test 'duplicated id in Batch validate'
    # at t/client.t line 263
    # expected: 'ping'
    #      got: '19'

    # Failed test 'amount of Responses in Batch different than expected validate'
    # at t/client.t line 283
    # Actual type: X::AdHoc
    # Looks like you failed 9 tests of 39
    t/client.t .. 
    Dubious, test returned 9 (wstat 2304, 0x900)
    Failed 9/39 subtests 
    t/server.t .. ok

    Test Summary Report
    -------------------
    t/client.t (Wstat: 2304 Tests: 39 Failed: 9)
      Failed tests:  24-25, 31-37
      Non-zero exit status: 9
    Files=2, Tests=68, 13 wallclock secs ( 0.04 usr  0.00 sys + 12.31 cusr  0.10 csys = 12.45 CPU)
    Result: FAIL
    test stage failed for JSON::RPC: Tests failed
      in method throw at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
      in method install at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
      in method resolve at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at /home/qlx4r/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
      in block <unit> at /home/qlx4r/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:95

    Failure Summary
    ----------------
    JSON::RPC(
        *test stage failed for JSON::RPC: Tests failed)

**Comment by qlx4r** [comment]
panda version:

> 2015.06-93-gefc2ff3

**Comment by bbkr** [comment]
There was a Great List Refactor compatibility issue fixed in https://github.com/bbkr/jsonrpc/pull/16 .

Does the problem still occur on fresh latest Rakudo/Panda install?

**Comment by teodozjan** [comment]
Now it is fine

**Comment by qlx4r** [comment]
close, but no cigar… one test failing, here's the output

    qlx4r@qp11 ~$ panda install JSON::RPC
    ==> Fetching JSON::RPC
    ==> Building JSON::RPC
    ==> Testing JSON::RPC

    # Failed test 'amount of Responses in Batch different than expected validate'
    # at t/client.t line 283
    # Actual type: Any
    # Looks like you failed 1 test of 39
    t/client.t .. 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/39 subtests 
    t/server.t .. ok

    Test Summary Report
    -------------------
    t/client.t (Wstat: 256 Tests: 39 Failed: 1)
      Failed test:  37
      Non-zero exit status: 1
    Files=2, Tests=68, 12 wallclock secs ( 0.04 usr  0.00 sys + 12.21 cusr  0.12 csys = 12.37 CPU)
    Result: FAIL
    test stage failed for JSON::RPC: Tests failed
      in method throw at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
      in method install at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
      in method resolve at /home/qlx4r/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at /home/qlx4r/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
      in block <unit> at /home/qlx4r/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:95


    Failure Summary
    ----------------
    JSON::RPC(
        *test stage failed for JSON::RPC: Tests failed)

**Comment by bbkr** [comment]
I cannot reproduce this error.
Are you sure you don't have any leftovers from previous versions?
Can you try to backup ~/.rakudobrew directory and start from scratch?

```
This is perl6 version 2015.07.1-943-g7662c46 built on MoarVM version 2015.08-34-g113c3b5
bbkr:jsonrpc bbkr$ panda install JSON::RPC
==> Fetching JSON::RPC
==> Building JSON::RPC
==> Testing JSON::RPC
t/client.t .. ok
t/server.t .. ok
All tests successful.
Files=2, Tests=68, 12 wallclock secs ( 0.03 usr  0.01 sys + 11.38 cusr  0.27 csys = 11.69 CPU)
Result: PASS
==> Installing JSON::RPC
Copying blib/lib/JSON/RPC/Client.pm to /Users/bbkr/.rakudobrew/moar-nom/install/share/perl6/site/lib/JSON/RPC/Client.pm
Copying blib/lib/JSON/RPC/Server.pm to /Users/bbkr/.rakudobrew/moar-nom/install/share/perl6/site/lib/JSON/RPC/Server.pm
Copying blib/lib/X/JSON/RPC.pm to /Users/bbkr/.rakudobrew/moar-nom/install/share/perl6/site/lib/X/JSON/RPC.pm
==> Successfully installed JSON::RPC
```

**Comment by qlx4r** [comment]
did a complete rebuild of moar and panda, and now JSON::RPC installs fine. thanks a lot
