### ISSUE TITLE
Failing tests - ran less tests than planned

### ISSUE THREAD

**Issue by vytas-dauksa** [bbkr/jsonrpc#21]
vytas-local@vytas-desktop:/tmp$ perl6 -v
This is perl6 version 2015.09-355-g06fef86 built on MoarVM version 2015.09-79-gee9fc2b

vytas-local@vytas-desktop:/tmp$ panda install Task::Star
[...]
==> Building JSON::RPC
==> Testing JSON::RPC
**Request id is different than response id (-32000): {:request(${:id(Any:U), :jsonrpc("2.0"), :method("ping")}), :response(${:id(Any), :jsonrpc("2.0"), :result("pong")})}
# Looks like you planned 39 tests, but ran 29**
t/client.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 10/39 subtests 
t/server.t .. ok

Test Summary Report
-------------------
t/client.t (Wstat: 65280 Tests: 29 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 39 tests but ran 29.
Files=2, Tests=58, 14 wallclock secs ( 0.03 usr  0.01 sys + 13.40 cusr  0.18 csys = 13.62 CPU)
Result: FAIL
test stage failed for JSON::RPC: Tests failed
  in method throw at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
  in method install at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
  in block  at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:214
  in method resolve at /home/vytas-local/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:208
  in sub MAIN at /home/vytas-local/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
  in block <unit> at /home/vytas-local/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:145

Failure Summary
----------------
Task::Star(
	*test stage failed for JSON::RPC: Tests failed)

**Comment by bbkr** [comment]
Thanks for the report.

Smileys in latest Rakudo broke test. Fixed in https://github.com/bbkr/jsonrpc/commit/f4259f122acec227ee1d0a657da7c0036b05d5bb
