### ISSUE TITLE
refactor exceptions

### ISSUE THREAD

**Issue by bbkr** [bbkr/jsonrpc#27]
Currently exceptions are in X::JSON::RPC::WhatWentWrong form, while best practice is JSON::RPC::X::WhatWentWrong.

Check ecosystem for potential compatibility breaks.

**Comment by azawawi** [comment]
Check stalled? :)

**Comment by azawawi** [comment]
@bbkr Proceeding with fix... No potential incompatibility problems as of September 2016

**Comment by azawawi** [comment]
@bbkr On second thought, please close this issue. Please see the discussion and rationale in [#perl6](https://irclog.perlgeek.de/perl6/2017-01-18#i_13942222).

**Comment by bbkr** [comment]
Moved to https://github.com/bbkr/jsonrpc/issues/32
