### ISSUE TITLE
Refactoring roadmap.

### ISSUE THREAD

**Issue by bbkr** [bbkr/jsonrpc#32]
This is really old module - it was started back in 2010 when Rakudo was running on ParrotVM and spec (especially concurrency parts) was in flux. Moreover - it started as JSON-RPC 1.0 client, while 2.0 spec brought significant changes that requires better abstraction to avoid messy procedural code flow.

What needs to be done:
* Separate transport from protocol. JSON RPC (except dead 1.1 spec) is transport independent and all transport code should be moved to roles with modules they use marked as recommended instead of mandatory.
* Make JSON decoder also pluggable, so users can choose if they want to use generic JSON::Tiny or JSON::Fast at the cost of hardwired nqp:: calls.
* Decide if exceptions should follow JSON::RPC::X::WhatHappened schema. I really don't like polluting global X::* namespace even if Rakudo can handle auth and ver module loading quite well. Also in X::JSON::RPC::Foo::Bar it is not clear where base package name ends and specific exception namespace starts. This is related to https://github.com/perl6/user-experience/issues/11 .
* Fix edge cases where bare values are allowed on top JSON level - see https://github.com/moritz/json/issues/22 .
* Design good abstraction objects for Request/Response/Batch/Error that will allow 2 things mentioned below.
* Parallel batch processing. It should be up to user to include OO::Monitors in application to disable parallelism if needed.
* Refactor Batch interface. Current one is very user unfriendly. For `[A,B]` request where A is notification, and B is regular request response will look like `[B]`, forcing user to recalculate stack positions. If client calls B he should be able to retrieve response directly from this call. I'm not sure what would be the best interface. Maybe `$response = $client.method_call()` single calls should look like `$promise = $client.'rpc.batch'.method_call()` in Batches so clients can get response directly from Promise object without stack recalculations? Promises looks... promising, because they may also allow to start batch processing my `$batch = $client.'rpc.batch'(); await $batch` instead of special `$batch->flush` keyword.
* Notifications should be asynchronous by design. That makes usage of Promises in Batches even better idea because interface will be consistent.
* Add OS X tests.
* Check for performance regressions.
* Check for Star modules presence or drop JSON::RPC from Star distribution to get more freedom in dependencies area.
* Review and merge changes from https://github.com/bbkr/jsonrpc/pull/31

**Comment by azawawi** [comment]
Thanks for the informative roadmap. Looks good so far.  A couple of comments/questions:

- Regarding **OS X tests**, I already added that for Travis CI in #31.
- I totally agree with you on the exception naming policy. It is better for the future.
- Please let us make these into small phases to speed up delivery of the refactor branch.
- Personally I would separate Client and Server into separate modules.
- A quick ack in [perl6-all-modules](https://github.com/moritz/perl6-all-modules) reveals that the list is fairly small:
```
stmuk/p6-task-galaxy/META6.json
teodozjan/lacuna-cookbuk/META.info
azawawi/perl6-odoo-client/META6.json
azawawi/perl6-electron/META.info
tadzik/Task-Star/META.info
```

How can I help? 👍

**Comment by bbkr** [comment]
Thanks for comments.

I thought about separating Client and Server and I'll decide when I'll have some OO code ready and see how much they share.

For basic Client flow it goes like:
* Method foo is called on Client.
* Client creates Request object from method name and method params.
* Request object is packed to JSON
* JSON request goes to transport
* JSON response arrives from transport
* Response object is created from JSON
* Response object is assigned to Request object (matching IDs)
* Response result is returned by Client as foo method output.

For basic Server flow it goes like:
* JSON arrives from transport
* Request object is created from JSON
* Method is searched in application
* Method params are validated
* Method is called in application context
* Response object is built from method output and Request ID
* Response is packed to JSON
* JSON is sent to transport

So even if Request and Response objects are in both flows they are not as reusable as it looks because in counterpart they work "in reverse", therefore require different constructors and method signatures. That's pro-split argument. On the other hand errors are common and probably transport / JSON plugins will be too. Hard to tell now how much copy-pasting there will be after split.

**Comment by azawawi** [comment]
Fair enough. Keep client and server in the same package. No need for that change.

**Comment by stmuk** [comment]
It would help Rakudo Star (R*) if it could be removed from that distro (at least for the time being) since it helps with replacing LWP::Simple in R*  (which JSON::RPC uses) with HTTP::Useragent.

**Comment by bbkr** [comment]
Because this protocol is stale (last spec update in 2013, almost dead discussion forum with 2 posts per month, no new services using it) I've decided to just maintain this module to be compatible with latest Rakudo / Star without major refactoring.
