### ISSUE TITLE
Example client/server - client gives error 

### ISSUE THREAD

**Issue by apapas** [bbkr/jsonrpc#33]
With example Client/Server the client outputs:

`Parse error (-32700): "Input (0 characters) is not a valid JSON string"`

`$ perl6 -v
This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-53-g66c6dda
implementing Perl 6.c.`

**Comment by bbkr** [comment]
I think this was caused by psgi.input -> p6sgi.input change. Already fixed.
