### ISSUE TITLE
Can this module be made to work with gRPC to access Google Drive?

### ISSUE THREAD

**Issue by tbrowder** [bbkr/jsonrpc#39]

**Comment by bbkr** [comment]
I'm not sure I understand the question. JSON-RPC and gRPC are completly different protocols, and Google Cloud does not support JSON-RPC syntax. Can you elaborate please?

**Comment by tbrowder** [comment]
I'm sorry for my misunderstanding. I was looking for an existing Raku module that is close to a possible solution for access to Google Drive. Their docs mention gRPC--hence my query.

**Comment by bbkr** [comment]
Closing as not related to this module. Proper gRPC support in Raku is on a wishlist for a long time: https://perl-foundation-outreach.github.io/gsoc-2021-ideas/raku/gRPC.html
